base:
  device: CUDA
  env_path: ./my_env
  view_mode: 2
inference:
  IP: 203.135.98.31
  model: LSTM
  port: 37942
  source: assets/test.mp4
train:
  batch_size: 4
  divide_present: 0.8
  epoch: 100
  gamma: 0.95
  lr: 0.001
  model: LSTM
  step_size: 1
