base:
  device: NVIDIA pytorch
  platform: pc
  pose_net: ov
  env_path: D:\code\python3.10\Lib
  size: 256x256
  view_mode: 3
inference:
  IP: 203.135.98.31
  model: micronet_m3
  port: 37942
  source: assets/test.mp4
train:
  Normalized_matrix:
  - - 0.485
    - 0.456
    - 0.406
  - - 0.229
    - 0.224
    - 0.225
  batch_size: 16
  divide_present: 0.8
  epoch: 50
  gamma: 0.95
  learn_rate: 0.001
  model: resnet18
  show_mode: Simple
  step_size: 1
  write_process: false
